### ISSUE TITLE
RPM packaging

### ISSUE THREAD

**Issue by dcode** [google/stenographer#104]
both deb and rpm packaging should be relatively simple using FPM. Just need to determine dependencies (which is the more annoying part anyway).

**Comment by dcode** [comment]
This can be closed.

Also I made a chef recipe to install and configure using my RPM. TODO includes adding deb support and/or compiling from source. PR's welcome ;-)

https://github.com/dcode/chef-stenographer/tree/master

**Comment by charlesfair** [comment]
“Bro” hugz!

(from Zac Thompson)

Chuck
