### ISSUE TITLE
stenographer fails to compile due to to leveldb dependency errors

### ISSUE THREAD

**Issue by hosom** [google/stenographer#111]
While this is not a bug with stenographer, I wanted to make you aware that stenographer will not compile due to an invalid reference in the leveldb dependency. I have submitted a bug report and instructions on how to fix the issue on code.google.com for leveldb:

https://code.google.com/p/leveldb-go/issues/detail?id=19&thanks=19&ts=1433245062

**Comment by gconnell** [comment]
Thanks for the report!  I'll reach out internally to the leveldb folks.

**Comment by gconnell** [comment]
Forgot to close this, but this was fixed in the leveldb source.
