### ISSUE TITLE
stenotype build error: __NR_fstat64’ was not declared in this scope

### ISSUE THREAD

**Issue by schwo** [google/stenographer#113]
Trying to build/install the current master on Ubuntu.

-- output of ./install.sh
Making sure we have sudo access
Killing aleady-running processes
stop: Unknown instance: 
Checking for package 'libaio-dev'
Checking for package 'libleveldb-dev'
Checking for package 'libsnappy-dev'
Checking for package 'g++'
Checking for package 'libcap2-bin'
Checking for package 'libseccomp-dev'
Building stenographer
`stenographer' -> `/usr/bin/stenographer'
Building stenotype
/data/stenographer/gopath/src/github.com/google/stenographer/stenotype /data/stenographer/gopath/src/github.com/google/stenographer
g++ -std=c++0x -g -Wall -fno-strict-aliasing -rdynamic -O2 -fPIC -fPIE -pie -fstack-protector -D_FORTIFY_SOURCE=2 -c -o stenotype_gcc.o stenotype.cc
stenotype.cc: In function ‘void st::CommonPrivileges(scmp_filter_ctx)’:
**stenotype.cc:269:3: error: ‘__NR_fstat64’ was not declared in this scope
stenotype.cc:278:3: error: ‘__NR_mmap2’ was not declared in this scope
stenotype.cc:286:3: error: ‘__NR_sigreturn’ was not declared in this scope**
util.h: At global scope:
util.h:55:6: warning: ‘{anonymous}::run_init_time’ defined but not used [-Wunused-variable]
make: *** [stenotype_gcc.o] Error 1

**Comment by gconnell** [comment]
Try pulling down again and let me know if you have any issues.

**Comment by schwo** [comment]
All good now. Thanks!
