### ISSUE TITLE
Any concerns/experience writing to a distributed file system, e.g., Ceph?

### ISSUE THREAD

**Issue by capveg** [google/stenographer#142]
Hi,

I'm looking at Stenographer and it looks great.  I was wondering if anyone has any experience or if there are any obvious issues with writing to a large distributed disk, e.g., Ceph's RDB block storage.

Thanks in advance.

**Comment by gconnell** [comment]
No personal experience.  Is Ceph over the network?  If so, make sure you're
not sniffing the packets containing the data you're writing, or you'll
quickly peg your bandwidth.  Otherwise, if it's a well-behaving block
device, not sure about throughput but the basic concept should work.

**Comment by capveg** [comment]
Yes, Ceph is over the network, but generally you have dedicated interfaces for it so no need to be concerned about a network feedback loop.

I'm setting up some trials and will let you know what I find.  Thanks for the response.

- Rob
.
