### ISSUE TITLE
stenotype make fail

### ISSUE THREAD

**Issue by sneakymonk3y** [google/stenographer#146]
Trying to compile on Raspberry Pi raspbian.
4.4.21-v7+ #911 SMP Thu Sep 15 14:22:38 BST 2016 armv7l GNU/Linux

~/.go/src/github.com/google/stenographer# make
errors with 

`g++ -std=c++0x -g -Wall -fno-strict-aliasing  -rdynamic -O2 -fPIC -fPIE -pie -fstack-protector -D_FORTIFY_SOURCE=2 -c -o stenotype_gcc.o stenotype.cc
In file included from packets.h:31:0,
                 from aio.h:24,
                 from stenotype.cc:80:
stenotype.cc: In function ‘void st::CommonPrivileges(scmp_filter_ctx)’:
stenotype.cc:290:41: error: ‘__NR_mmap’ was not declared in this scope
   SECCOMP_RULE_ADD(ctx, SCMP_ACT_ALLOW, SCMP_SYS(mmap), 0);
                                         ^
util.h:219:44: note: in definition of macro ‘CHECK_SUCCESS’
     ::st::Error __check_success_error__ = (x);                             \
                                            ^
stenotype.cc:290:3: note: in expansion of macro ‘SECCOMP_RULE_ADD’
   SECCOMP_RULE_ADD(ctx, SCMP_ACT_ALLOW, SCMP_SYS(mmap), 0);
   ^
util.h: At global scope:
util.h:55:6: warning: ‘{anonymous}::run_init_time’ defined but not used [-Wunused-variable]
 bool run_init_time = InitTime();
      ^
Makefile:80: recipe for target 'stenotype_gcc.o' failed
make: *** [stenotype_gcc.o] Error 1`

Any help?

**Comment by gconnell** [comment]
Please pull from master and see if it works.  I think https://github.com/google/stenographer/commit/8ef0b15a812317885b3d4e5ae4286d7dbbe350b5 should fix this.
