### ISSUE TITLE
Mac OS X port?

### ISSUE THREAD

**Issue by mathie** [google/stenographer#96]
Out of curiosity, what sort of effort do you think would be required to port stenographer to Mac OS X? I'm getting one error from `go build`:

    # github.com/google/stenographer/blockfile
    blockfile/blockfile.go:36:11: fatal error: 'linux/if_packet.h' file not found
     #include <linux/if_packet.h>
              ^
    1 error generated.

Is that a more performant mechanism to get the raw packets than going through libpcap? If so, would it be possible to fall back on a libpcap implementation for other platforms? (I don't really know what I'm talking about here!)

**Comment by gconnell** [comment]
Unfortunately, at the moment porting to OSX, or really any non-Linux, would be really hard.  stenographer depends very heavily on AF_PACKET, a linux-only kernel feature, for packet capture.  This dependency is very deeply embedded, and it would take a good bit of work to get around it.

The Go code, as you've seen, is pretty language-agnostic.  The C++ code, specifically stenotype/packets.cc, is where the real dependency comes into play.

We could fall back to libpcap, I guess, but with a drastic performance degradation.  steno really is all about performance, so I'm not sure this is worth the effort.

**Comment by DubhAd** [comment]
It would be interesting to know what that impact would be. I'm using capture cards (Emulex DAG), which don't provide a network interface, but do support a modified libpcap. Stenographer has the features I want, but requiring AF_PACKET means it's unusable for me, which is frustrating :)
